spring:
  application:
    name: backend-api

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.sxiyrycwruzxwpqehdmo
    password: ZR4PEp5RzIYaTKV7
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


app:
  storage:
    max-file-size-bytes: 20971520  # 20MB
    endpoint: https://sxiyrycwruzxwpqehdmo.storage.supabase.co/storage/v1/s3
    region: ap-southeast-1
    bucket: documents
    access-key: 585ae45733fdca5210aff3e943f0875d
    secret-key: 0c47c1b803b925f875f777cf47133ab401575eeb3eed3b95aa42831edf997f54
    signed-url-minutes: 15

server:
  address: 0.0.0.0
  compression:
    enabled: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

